# Generated by ormin_importer. DO NOT EDIT.

type
  Attr = object
    name: string
    tabIndex: int
    typ: DbTypekind
    key: int   # 0 nothing special,
               # +1 -- primary key
               # -N -- references attribute N
const tableNames = [
  "place"
]

const attributes = [
  Attr(name: "id", tabIndex: 0, typ: dbSerial, key: 1),
  Attr(name: "name", tabIndex: 0, typ: dbVarchar, key: 0),
  Attr(name: "lnglat", tabIndex: 0, typ: dbGeometry, key: 0)
]
